### ISSUE TITLE
Ques about details.

### ISSUE THREAD

**Issue by huixiancheng** [valeoai/rangevit#5]
1. Since PixelShuffle don't work on patch_embed like 2x8, use Rearrange instead of it. Altough look like the working way is very similar, how about it's effect on performance? Eg: Also use Rearrange on 8x8 downsample, shou it better or worser than PixelShuffle? Btw, It looks similar to [PatchExpand](https://github.com/HuCaoFighting/Swin-Unet/blob/451e51d840e19a1c3c7ee6711f5a303ce12bdfa9/networks/swin_transformer_unet_skip_expand_decoder_sys.py#L333-L355) in SwinUnet.
https://github.com/valeoai/rangevit/blob/4484d35b656f8213d887754780a4aa1e23303ea3/models/decoders.py#L72-L79
2. I'm not sure the useage of this F.interpolate ops, it's mean that the feature size of encoder-decoder output will be not same as input (in some time)? 
https://github.com/valeoai/rangevit/blob/4484d35b656f8213d887754780a4aa1e23303ea3/models/rangevit.py#L229-L231
3. Since RangeViT only use final layer feature map to upsample and cat with skip connetction, I'm not sure this is the original idea to keep the model simple and efficient. Have you ever tried PUP or MLA structures similar to [SETR](https://openaccess.thecvf.com/content/CVPR2021/papers/Zheng_Rethinking_Semantic_Segmentation_From_a_Sequence-to-Sequence_Perspective_With_Transformers_CVPR_2021_paper.pdf)? Mentioning this since only mentioned segmenter in paper.

**Comment by huixiancheng** [comment]
By the way, the lantency on Table 10 is test on sliding-window or whole range images?
![image](https://github.com/valeoai/rangevit/assets/65054204/dd748896-8d69-4ab0-952d-f4aea8f75520)

**Comment by angelika1108** [comment]
Hi @huixiancheng! We are sorry for the late reply and we thank you very much for your questions!

1. As PixelShuffle doesn't work for non-square `scale_factor`, we use einops Rearrange instead. As it is equivalent to PixelShuffle, it shouldn't affect the performance. Indeed, we could have used Rearrange on a square `scale_factor`, and it would have been equivalent to PixelShuffle. Yes, it's exactly like [PatchExpand](https://github.com/HuCaoFighting/Swin-Unet/blob/451e51d840e19a1c3c7ee6711f5a303ce12bdfa9/networks/swin_transformer_unet_skip_expand_decoder_sys.py#L333-L355) in SwinUnet (just the channel dimension is the last dimension in SwinUnet).

2. We needed the `F.interpolate()` in the case of the "Linear decoder", which outputs a feature map with spatial dimension `[H/P_H, W/P_W]`, where the patch size is `[P_H, P_W]`. So, the `F.interpolate()` bilinearly upsamples the feature map to the same spatial dimension as the input image `[H, W]`. You are right that we don't need the `F.interpolate()` in the case of the "UpConv" decoder as the spatial dimension of the output of the decoder is already `[H, W]`. This is because we use the same `scale_factor` as the `patch_size`. However, if someone wants to use a different (smaller) `scale_factor` than the `patch_size`, then the  `F.interpolate()` is necessary to produce a feature map that has spatial dimension `[H, W]`.

3. Yes, we wanted to keep the model architecture as simple as possible. The "Linear decoder" is inspired by the "Linear decoder" of [Segmenter](https://arxiv.org/pdf/2105.05633.pdf) (Sec. 3.2) but we use the "UpConv decoder" in our final model, which is still simple, but more efficient thanks to the PixelShuffle layer and skip connection. We haven't tried different decoder architectures, but it's a good idea for a future direction!

4. The inference time in Table 10 refers to whole range images.

**Comment by huixiancheng** [comment]
Thx for your kind reply~!
